### PR TITLE
feat: use new jekyll theme

### PR DESCRIPTION
**Pull request by Slashgear**
The idea of this PR is to make a fresh design update of our tech blog with a new jekyll blog theme.
Found that one which is really nice and simple.

We still need to update a lot a post metadatas ⚠️

### CODE REVIEW

**Review by Oliboy50 — APPROVED** [review]
😲 💯 💯 💯 😲 

I didn't check the whole code, but I played with the preview and it's pretty nice 👏

**Review by Melfo01 — APPROVED** [review]
👌 Great idea

**Comment by pmartin** [comment]
50k lignes 😱 pas regardé le code non plus, navigué un peu sur la preview, ça me semble top :+1:

**Review by fdubost — COMMENTED** [review]
Nice theme 💅 
Some posts have lost their images, ex. https://tech.bedrockstreaming.com/spa-mode-isomorphism-js/ vs https://pr-296.dsvmt7xpjktgx.amplifyapp.com/2017/05/17/spa-mode-isomorphism-js.html
URLs change, isn't a problem for SEO? We should maybe handle 301 🙄

**Comment by Slashgear** [comment]
@fdubost 

> Some posts have lost their images, ex. https://tech.bedrockstreaming.com/spa-mode-isomorphism-js/ vs https://pr-296.dsvmt7xpjktgx.amplifyapp.com/2017/05/17/spa-mode-isomorphism-js.html

I did not update all image metadata (there is a new format now) I wanted to validate the theme before doing it manually ^^

> URLs change, isn't a problem for SEO? We should maybe handle 301 🙄

It is not that bad for this blog, there is no great solution for Github pages hosting redirection sadly

**Review by kennydee — APPROVED** [review]
Je ne regarde pas le code non plus mais j'aime bcp la lisibilité du thème, bravo.
Seul petite remarque, l'auteur, et ses liens réseaux sociaux sont peu ou pas visible du tout.
Je trouvais ca intéressant pour vous d'avoir une petite mise en avant de vos RS sur vos articles. WYT @Slashgear ?

**Comment by Slashgear** [comment]
@kennydee 

> Je trouvais ca intéressant pour vous d'avoir une petite mise en avant de vos RS sur vos articles. WYT @Slashgear ?

Malheureusement ce n'est pas disponible de base dans ce theme mais on peut le coder en faisant évoluer les mécaniques de gestion des "authors", ça se fait dans un temps 2

**Comment by Slashgear** [comment]
ℹ️ The huge diff on the PR is due to theme code change, not sure code review is necessary here 😄

**Comment by vgallissot** [comment]
Nice one, I like the new design!!
Like @kennydee said, we loose some interesting infos from author.

especially, the title, the author (+twitter/github) and the date of the publication are affixed on the main image, which makes both quite illegible on most articles, is it on this part that you thought to work manually?

**Comment by Slashgear** [comment]
@vgallissot 

Same answer for authors subject, this is not handled by default by this theme sadly.

In this theme, main image should be dark themed to make it readable, I will check if there is an option for text color but I am not sure. If not, this will mean dropping images from those articles.

**Comment by Slashgear** [comment]
@vgallissot @kennydee 

I found a solution for authors, there is a way of doing it in this theme.
There is a `author.yml` file in which we could refer author by id, name, avatar and one url.
✅ 
This is better than the previous theme, because we only have to maintain once for every post.

For feature Image, I am on it:
- We could change images ? (not a good idea
- We can hide the title ? there is an option for that
- We can use default transparent image with a color like this example https://sylhare.github.io/Type-on-Strap/2019/05/18/color-post.html

**Review by yverry — APPROVED** [review]

**Comment by vgallissot** [comment]
nice for authors, good job :+1: 
I think using default transparent image is a good idea.
Good to me :ok_hand:

**Review by vgallissot — APPROVED** [review]

**Review by fdubost — APPROVED** [review]
Shiny 👍

**Review by oltodo — APPROVED** [review]
Great work!

**Pull request merged**
